# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:        pretty
markdown:         redcarpet
pygments:         true
# relative_permalinks: true

# Setup
title:               UNGA Statement Analysis
tagline:             
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joseph Bullock
  url:               https://twitter.com/josephpbullock

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
